# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe702d1effba380e00578db96839b4d7962416843e6df2c8950a003beffd0038e2986ce477adfc58a628b3e1e06a528e7766547aa48cce6a256df9a6be4a7352

test:
  secret_key_base: e7b8decd5f46ed844f526a71ed758c54172bbaa87e9fa93734b8c0061a60049ee3b5117a4556c42d8a94d36d7e6b770e6646eda0150914cbd73c07dfc7655262

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
